# Generated by Django 3.2.8 on 2022-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(choices=[('NONE', ''), ('Standard Delivery', 'Standard Delivery'), ('Next Day Delivery', 'Next Day Delivery'), ('Week Delivery', 'Week Delivery')], help_text='Required', max_length=255, verbose_name='delivery_name')),
                ('delivery_region', models.CharField(choices=[('None', ''), ('Island', 'Island'), ('Mainland', 'Mainland'), ('Outliers', 'Outliers'), ('NW', 'North West'), ('NE', 'North East'), ('NC', 'North Central'), ('SW', 'South West'), ('SE', 'South East'), ('SS', 'South South')], help_text='Required', max_length=255, null=True, verbose_name='delivery_location')),
                ('delivery_price', models.IntegerField(verbose_name='delivery price')),
                ('delivery_method', models.CharField(choices=[('In Store', 'In Store'), ('Home Delivery', 'Home Delivery')], help_text='Required', max_length=255, verbose_name='delivery_method')),
                ('delivery_timeframe', models.CharField(choices=[('24hours', '24hours'), ('48hours', '48hours'), ('72hours', '72hours')], help_text='Required', max_length=255, verbose_name='delivery timeframe')),
                ('delivery_window', models.CharField(choices=[('None', ''), ('5.00am', '5.00am to 10.00pm'), ('10.00am', '10.00am to 3.00pm'), ('3.00pm', '3.00pm to 7.00pm'), ('7.00pm', '7.00pm to 12.00pm')], help_text='Required', max_length=255, verbose_name='delivery window')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
            },
        ),
        migrations.CreateModel(
            name='PaymentSelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Paystack', 'Paystack'), ('Paypal', 'Paypal'), ('Stripe', 'Stripe')], help_text='Required', max_length=255, verbose_name='name')),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment Selection',
                'verbose_name_plural': 'Payment Selections',
            },
        ),
    ]
